[package]
name = "dircheck"
version = "0.1.1"
edition = "2021"

[dependencies]
blake3 = { version = "1", features = ["rayon"] }
const-hex = "1.12.0"
memmap2 = "0.9"
rayon = "1.10"
structopt = "0.3"
thiserror = "1.0"
walkdir = "2.5"
